### ISSUE TITLE
Errors while creating consensus clusters

### ISSUE THREAD

**Issue by madalenamrp** [charles-plessy/CAGEr#27]
First of all, thank you for developing and continuously improving CAGEr. I am interested in extracting  sequences flanking the TSSs from the 12 zebrafish developmental time-points previously analysed with CAGEr (data from Nepal et al., 2013 and further explored in Haberle et al., 2014). Additionally, I would also like to recover transcript identity for each dominant TSS.  

I first tried using CAGEr (version 1.28.0) following the package vignette and encountered no problems, using the data provided in Haberle et al., 2014. This data was originally aligned to an older zebrafish genome assembly version. As I would like to extract sequence information based on the genomic coordinates of the TSSs, I have remapped the raw sequencing data to the most recent zebrafish genome assembly, GRCz11/danRer11, and I am currently running CAGEr using the BSgenome.Drerio.UCSC.danRer11 package (that I forged myself). 

Analysis was performed as follows:

myCAGEset_danRer11 <- new("CAGEset",
genomeName = "BSgenome.Drerio.UCSC.danRer11",
inputFiles = pathsToInputFiles,
inputFilesType = 'bam',
sampleLabels = sampleLabels)

getCTSS(myCAGEset_danRer11,
removeFirstG = T,
correctSystematicG = T) 

plotReverseCumulatives(myCAGEset_danRer11,
fitInRange = c(5, 1000),
onePlot = TRUE)

normalizeTagCount(myCAGEset_danRer11,
method = "powerLaw",
fitInRange = c(5, 1000),
alpha = 1.20,
T = 1*10^6) # according to values returned by "plotReverseCumulatives"

clusterCTSS(object = myCAGEset_danRer11,
threshold = 1,
thresholdIsTpm = TRUE,
nrPassThreshold = 1,
method = "distclu",
maxDist = 20,
removeSingletons = TRUE,
keepSingletonsAbove = 5) 

cumulativeCTSSdistribution(myCAGEset_danRer11, clusters = "tagClusters")

quantilePositions(myCAGEset_danRer11,
clusters = "tagClusters",
qLow = 0.1,
qUp = 0.9)

aggregateTagClusters(myCAGEset_danRer11,
tpmThreshold = 5,
qLow = 0.1,
qUp = 0.9,
maxDist = 100)

This is where I got the first error: 
"Error in validObject(x) : invalid class “IRanges” object: 
   'width(x)' cannot contain negative integers."

Traceback() indicates that the error arises when generating the TC.list: 

TC.list <- tagClustersGR(object, returnInterquantileWidth = TRUE,  qLow = qLow, qUp = qUp)
TC.list <- endoapply(TC.list, function(x) {
start(x) <- mcols(x)[[paste0("q_", qLow)]] + start(x)
end(x)   <- mcols(x)[[paste0("q_", qUp)]]  + start(x)
x})

Since start(x) is calculated before end(x), I believe that in some instances end(x) will be assigned a position that is outside (downstream) of the tag cluster range. This error was resolved by swapping the calculation order:

TC.list <- endoapply(TC.list, function(x) {
end(x) <- mcols(x)[[paste0("q_", qUp)]] + start(x) 
start(x) <- mcols(x)[[paste0("q_", qLow)]] + start(x)

I am unsure however if it could have to do with the new zebrafish genome annotation? Has anyone else encountered this error before while analyzing other samples?

When changing the code, the aggregateTagClusters() runs further but returns a second error:
" Error in validObject(.Object) : 
  invalid class “ConsensusClusters” object: Consensus clusters must not overlap with each other."

I then tried running the "paraclu" clustering method, that allows to remove overlapping tag clusters:

clusterCTSS(object=myCAGEset_danRer11,
threshold=1,
thresholdIsTpm=TRUE,
nrPassThreshold=1,
method="paraclu",
removeSingletons=TRUE,
keepSingletonsAbove=5,
minStability = 1,
reduceToNonoverlapping = TRUE)

cumulativeCTSSdistribution(myCAGEset_danRer11, clusters = "tagClusters") 

quantilePositions(myCAGEset_danRer11, clusters = "tagClusters", qLow = 0.1, qUp = 0.9)

aggregateTagClusters(myCAGEset_danRer11,
tpmThreshold = 5,
qLow = 0.1,
qUp = 0.9,
maxDist = 100)

However, I again get the error:
" Error in validObject(.Object) : invalid class “ConsensusClusters” object: Consensus clusters must not overlap with each other."

I assume that this is because for at least one of the twelve samples, one (or more) genomic position is being assigned to two distinct tag clusters. What would be your recommendation, for dealing with this error?

Note, that when using the "paraclu" clustering method I no longer get the previous error  "'width(x)' cannot contain negative integers." I don't understand why this is the case.

Your help and input would be highly appreciated!
Thank you,
Madalena

**Comment by fengj03** [comment]
I got the same error for analysis our data but I could not fix this problem.

The “invalid class ConsensusClusters object: Consensus clusters must not overlap with each other” issue was caused by the aggregateTagClusters step.

The “if (length (reduce(object, min.gapwidth=0L)) < length(object)) Return ("Consensus clusters must not overlap with each other.")” line is aim to determine that Consensus clusters should not overlap with each other.

In my case: 
“length (reduce(object, min.gapwidth=0L)) = 3” return
scaffold1	345416	623304	277889	+
scaffold1	419791	623308	203518	-
scaffold1	699358	699366	9	-

“length(object)” return
scaffold1	345416	623304	277889	+	3.8457	18693	3.845
scaffold1	419791	623308	203518	-	16.040	18694	16.040
scaffold1	419828	419860	33	-	1.555	18695	1.555
scaffold1	505745	505747	3	+	0.290	18692	0.290
scaffold1	699358	699366	9	-	2.699	18696	2.699

In length(object), line 1+ line 4 (as well, line 2 + line 3) should be merged into one consensus cluster.

**Comment by fengj03** [comment]
This issue could be fixed by sorting the object before findOverlaps in AggregationFunctions.R.

**Comment by fansalon** [comment]
Hi, I encountered the same problem Madalena reported above.

aggregateTagClusters(cage_bam, excludeSignalBelowThreshold = T,
                     tpmThreshold = 5, 
                     qLow = 0.1, qUp = 0.9, maxDist = 100,
                     useMulticore = T, nrCores = threads)

Error in validObject(x) : invalid class “IRanges” object: 
    'width(x)' cannot contain negative integers


This is my code:

inputFiles <- list.files(pattern = "*bam$", full.names = T, recursive = T)
sampleLabels <- str_split_fixed(inputFiles,"/",4)[,3]

cage_bam <- new("CAGEset", 
                genomeName = "BSgenome.danrer.ensembl.11", 
                inputFiles = inputFiles,
                inputFilesType = 'bam', 
                sampleLabels =  sampleLabels)

getCTSS(cage_bam,mappingQualityThreshold=0,removeFirstG = T, correctSystematicG = T,
        useMulticore = T, nrCores = threads)

cage_bam_ctss_notNorm <- CTSStagCount(cage_bam)

normalizeTagCount(cage_bam, method = "simpleTpm")

clusterCTSS( object = cage_bam,
             threshold = 1,                       
             thresholdIsTpm = T,                
             nrPassThreshold = 1,                  
             method = "distclu",                   
             maxDist = 20,                         
             removeSingletons = T,              
             keepSingletonsAbove = 5,              
             useMulticore = T, nrCores = threads)

cumulativeCTSSdistribution(cage_bam, clusters = "tagClusters",
			   useMulticore = T, nrCores = threads)

quantilePositions(cage_bam, clusters = "tagClusters", qLow = 0.1, qUp = 0.9,
                  useMulticore = T, nrCores = threads)

aggregateTagClusters(cage_bam, excludeSignalBelowThreshold = T,
                     tpmThreshold = 5, 
                     qLow = 0.1, qUp = 0.9, maxDist = 100,
                     useMulticore = T, nrCores = threads)

Here the following error rose:

Error in validObject(x) : invalid class “IRanges” object: 
    'width(x)' cannot contain negative integers


Is there a straight forward way to fix this?

Thanks.

Federico

**Comment by HannahVMeyer** [comment]
Hi Charles,
as an alternative to providing `CustomConsensusCluster`s (#25) I am interested in using the `clusterCTSS `with 'distclu' and `cumulativeCTSSdistribution` followed `aggregateTagClusters` to compute consensus clusters and compare with my externally provided ones. 

This runs successfully (R4.0.0, CAGEr_1.31.2, Bioconductor dev branch):
```r
> clusterCTSS(object = ce,
+             threshold = 5,
+             thresholdIsTpm = TRUE,
+             nrPassThreshold = 1,
+             maxDist=12,
+             method = "distclu")

Filtering out CTSSs below threshold...
Clustering...
	-> mESC1_x
	-> mESC2_x
	-> mESC1_fantom
	-> mESC2_fantom
> # Promoter width
> cumulativeCTSSdistribution(ce, clusters = "tagClusters", useMulticore = TRUE)

Calculating cumulative sum of CAGE signal along clusters...
	-> mESC1_x
	-> mESC2_x
	-> mESC1_fantom
	-> mESC2_fantom
> quantilePositions(ce, clusters = "tagClusters", qLow = 0.1, qUp = 0.9)

Getting positions of quantiles within clusters...
	-> mESC1_x
	-> mESC2_x
	-> mESC1_fantom
	-> mESC2_fantom
```
However, `aggregateClusters` fails as follows:
```r
> aggregateTagClusters(ce, tpmThreshold = 5, qLow = 0.1, qUp = 0.9,
+                      maxDist = 100)
Error in validObject(x) : invalid class “IRanges” object: 
    'width(x)' cannot contain negative integers
```
The options I provided are actually the defaults, running it without specifically providing them fails as well, but with different  error message:
```r
> aggregateTagClusters(ce)
Error in validObject(.Object) : 
  invalid class “ConsensusClusters” object: Consensus clusters must not overlap with each other.
```
However, although I think this error message is more meaningful, it is confusing, as the consensus clusters were computed by an `CAGEr` internal function, so they should be valid clusters?

I have tried with a number of different parameter values (tpmThreshold = 1/5/10/50, qLow = 0.3, qUp = 0.7, maxDist = 1/5/10/100/200), all fail with same error.

I am using the same dataset that I have previously shared with you, in case you can/want to follow up on this on a specific example.

Thank you again for your work on this and for your help in solving these issues!

**Comment by charles-plessy** [comment]
I had a look at the failure when default parameters are implied (not written). The internal function `.make.consensus.clusters()` reduces the overlapping TCs, applying optional thresholds and saves the result as consensus clusters. The TCs are then mapped back to the consensus clusters. Some TCs did not overlap the consensus clusters, and this caused the mapping information to be shifted, and the error propagated until it triggered the duplication of some consensus clusters.

It seems that I can correct that with the following patch:

```
diff --git a/R/AggregationFunctions.R b/R/AggregationFunctions.R
index 0100b6d..ae594c9 100644
--- a/R/AggregationFunctions.R
+++ b/R/AggregationFunctions.R
@@ -28,7 +28,8 @@ setMethod(".make.consensus.clusters", "GRangesList", function(TC.list, plus.minu
   # Annotate TCs with ID of the aggregated cluster they intersect with.
   gr.list <- endoapply( gr.list, function (gr) {
     o = findOverlaps(clusters.gr, gr)
-    gr$consensus.cluster <- queryHits(o)
+    gr$consensus.cluster <- "."
+    gr$consensus.cluster[subjectHits(o)] <- queryHits(o)
     gr$sample <- "tbd" # Can not retreive
     gr
   })
```

However, I am not sure if the fact that some TCs did not overlap the clusters is itself a bug or not. I need to doublecheck, but I have no time left this wee.

**Comment by HannahVMeyer** [comment]
Thank you Charles for following up on this. 

Could it be the tag clusters that do not pass the `tpmThreshold`  which do not overlap the consensus clusters and then cause an issue?

Or a potential clash of how the `tpmThreshold` and  `excludeSignalBelowThreshold` parameters are handled when constructing the consensus clusters versus the remapping of the tag clusters to the consensus clusters?

**Comment by HannahVMeyer** [comment]
Hi Charles, is there any chance you have an update on this? This function failing has created a bit of stop on my analyses. I really appreciate you looking into this issue and if you do not have time to work on this at the moment, I will look for a work around but wanted to check in first.

Thank you very much!

**Comment by charles-plessy** [comment]
Hi Hannah, I maybe will be able to investigate further next week.  But you can also try to go ahead with applying the patch above.  If you have difficulty to build a patched package, please let me know.

**Comment by HannahVMeyer** [comment]
Hi Charles, I have cloned the master branch and  included your patch and used devtools to install the package from source.

However, the error persists. Looking closer at this, the problem arises here:

```r
setMethod( ".aggregateTagClustersGR", "CAGEr"
         , function ( object, tpmThreshold
                    , qLow, qUp, maxDist) {
  if (all( !is.null(qLow), !is.null(qUp))) {
    TC.list <- tagClustersGR(object, returnInterquantileWidth = TRUE,  qLow = qLow, qUp = qUp)
    TC.list <- endoapply(TC.list, function(x) {
      start(x) <- mcols(x)[[paste0("q_", qLow)]] + start(x)
      end(x)   <- mcols(x)[[paste0("q_", qUp)]]  + start(x)
      x})
  } else {
    TC.list <- tagClustersGR(object)
  }
  consensus.clusters <- .make.consensus.clusters( TC.list = TC.list
                                                , plus.minus = round(maxDist/2)
                                                , tpm.th = tpmThreshold)
  consensus.clusters <- .clusterAggregateAndSum(consensus.clusters, "consensus.cluster")
  consensus.clusters <- GRanges(consensus.clusters)
  names(consensus.clusters) <- as.character(consensus.clusters)
  .ConsensusClusters(consensus.clusters)
})
```

with the patch, we fixed the `.make.consensus.clusters` function, however the error arises from further upstream, in 

```r
    TC.list <- endoapply(TC.list, function(x) {
      start(x) <- mcols(x)[[paste0("q_", qLow)]] + start(x)
      end(x)   <- mcols(x)[[paste0("q_", qUp)]]  + start(x)
      x})
```

with full traceback here:

```r
aggregateTagClusters(ce, tpmThreshold = 5, qLow = 0.1, qUp = 0.9,
+                      maxDist = 100)
 Error in validObject(x) : invalid class “IRanges” object: 
    'width(x)' cannot contain negative integers 
19.
stop(msg, ": ", errors, domain = NA) 
18.
validObject(x) 
17.
.set_IRanges_start(x, value) 
16.
`start<-`(ranges(x), ..., value = value) 
15.
`start<-`(ranges(x), ..., value = value) 
14.
`start<-`(`*tmp*`, value = mcols(x)[[paste0("q_", qLow)]] + start(x)) 
13.
`start<-`(`*tmp*`, value = mcols(x)[[paste0("q_", qLow)]] + start(x)) at AggregationMethods.R#165
12.
FUN(extractROWS(unlisted_X, IRanges(X_elt_start[i], X_elt_end[i])), 
    ...) 
11.
FUN(X[[i]], ...) 
10.
lapply(non_empty_idx, function(i) FUN(extractROWS(unlisted_X, 
    IRanges(X_elt_start[i], X_elt_end[i])), ...)) 
9.
lapply(non_empty_idx, function(i) FUN(extractROWS(unlisted_X, 
    IRanges(X_elt_start[i], X_elt_end[i])), ...)) 
8.
lapply_CompressedList(X, FUN, ...) 
7.
lapply(X, FUN, ...) 
6.
lapply(X, FUN, ...) 
5.
endoapply(TC.list, function(x) {
    start(x) <- mcols(x)[[paste0("q_", qLow)]] + start(x)
    end(x) <- mcols(x)[[paste0("q_", qUp)]] + start(x)
    x ... at AggregationMethods.R#164
4.
.aggregateTagClustersGR(object, tpmThreshold = tpmThreshold, 
    qLow = qLow, qUp = qUp, maxDist = maxDist) at AggregationMethods.R#155
3.
.aggregateTagClustersGR(object, tpmThreshold = tpmThreshold, 
    qLow = qLow, qUp = qUp, maxDist = maxDist) at AggregationMethods.R#113
2.
aggregateTagClusters(ce, tpmThreshold = 5, qLow = 0.1, qUp = 0.9, 
    maxDist = 100) at AggregationMethods.R#99
1.
aggregateTagClusters(ce, tpmThreshold = 5, qLow = 0.1, qUp = 0.9, 
    maxDist = 100) 
```

**Comment by charles-plessy** [comment]
Dear Hannah, I tried again to patch the current version of CAGEr (from Git) and it ran fine on the test data that you provided me.  I will push the changes to Bioconductor (3.12, currently _devel_); it might take a day or to to become visible.

**Comment by HannahVMeyer** [comment]
Thank you Charles. I will give try and let you know if it solved the issue.
Thanks!

**Comment by charles-plessy** [comment]
I have pushed the changes in version `1.30.2` in the current Bioconductor release (3.11) branch. Please open a new issue if there are still errors.

**Comment by HannahVMeyer** [comment]
Hi Charles,

Thanks for taking the time to look into this. Your changes to the  Bioconductor release (3.11) branch have not updated yet, I think, it is still version `1.30.1` there. Changes on the development branch are up to data  now and I have tried `CAGEr_1.31.2` (full session info below) but I still see the same error message: 

```r
clusterCTSS(object = ce,
            threshold = 5,
            thresholdIsTpm = TRUE,
            nrPassThreshold = 1,
            maxDist=12,
            method = "distclu")

# Promoter width
cumulativeCTSSdistribution(ce, clusters = "tagClusters", useMulticore = TRUE)
quantilePositions(ce, clusters = "tagClusters", qLow = 0.1, qUp = 0.9)
plotInterquantileWidth(ce, clusters = "tagClusters", tpmThreshold = 5,
                       qLow = 0.1, qUp = 0.9)

# Creating consensus promoters across samples
aggregateTagClusters(ce, tpmThreshold = 5, qLow = 0.1, qUp = 0.9)
Error in validObject(x) : invalid class “IRanges” object: 
    'width(x)' cannot contain negative integers
```

```r
R version 4.0.0 (2020-04-24)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets  methods  
[9] base     

other attached packages:
 [1] forcats_0.5.0               stringr_1.4.0               dplyr_1.0.0                
 [4] purrr_0.3.4                 readr_1.3.1                 tidyr_1.1.0                
 [7] tibble_3.0.2                ggplot2_3.3.2               tidyverse_1.3.0            
[10] DESeq2_1.29.6               CAGEr_1.31.2                MultiAssayExperiment_1.15.2
[13] SummarizedExperiment_1.19.5 DelayedArray_0.15.6         matrixStats_0.56.0         
[16] Matrix_1.2-18               Biobase_2.49.0              GenomicRanges_1.41.5       
[19] GenomeInfoDb_1.25.8         IRanges_2.23.10             S4Vectors_0.27.12          
[22] BiocGenerics_0.35.4        

loaded via a namespace (and not attached):
 [1] nlme_3.1-148             fs_1.4.2                 bitops_1.0-6            
 [4] lubridate_1.7.9          bit64_0.9-7              RColorBrewer_1.1-2      
 [7] httr_1.4.1               tools_4.0.0              backports_1.1.8         
[10] R6_2.4.1                 vegan_2.5-6              KernSmooth_2.23-17      
[13] DBI_1.1.0                mgcv_1.8-31              colorspace_1.4-1        
[16] permute_0.9-5            withr_2.2.0              tidyselect_1.1.0        
[19] bit_1.1-15.2             compiler_4.0.0           cli_2.0.2               
[22] rvest_0.3.5              xml2_1.3.2               rtracklayer_1.49.3      
[25] scales_1.1.1             genefilter_1.71.0        digest_0.6.25           
[28] Rsamtools_2.5.3          stringdist_0.9.5.5       XVector_0.29.3          
[31] pkgconfig_2.0.3          dbplyr_1.4.4             BSgenome_1.57.4         
[34] readxl_1.3.1             rlang_0.4.6              rstudioapi_0.11         
[37] RSQLite_2.2.0            VGAM_1.1-3               generics_0.0.2          
[40] jsonlite_1.7.0           BiocParallel_1.23.2      gtools_3.8.2            
[43] RCurl_1.98-1.2           magrittr_1.5             GenomeInfoDbData_1.2.3  
[46] fansi_0.4.1              Rcpp_1.0.5               munsell_0.5.0           
[49] lifecycle_0.2.0          stringi_1.4.6            MASS_7.3-51.6           
[52] zlibbioc_1.35.0          plyr_1.8.6               grid_4.0.0              
[55] formula.tools_1.7.1      blob_1.2.1               crayon_1.3.4            
[58] lattice_0.20-41          Biostrings_2.57.2        haven_2.3.1             
[61] splines_4.0.0            annotate_1.67.0          hms_0.5.3               
[64] locfit_1.5-9.4           beanplot_1.2             pillar_1.4.5            
[67] geneplotter_1.67.0       reprex_0.3.0             XML_3.99-0.4            
[70] glue_1.4.1               modelr_0.1.8             data.table_1.12.8       
[73] operator.tools_1.6.3     vctrs_0.3.1              cellranger_1.1.0        
[76] gtable_0.3.0             reshape_0.8.8            assertthat_0.2.1        
[79] xtable_1.8-4             broom_0.7.0              survival_3.2-3          
[82] som_0.3-5.1              GenomicAlignments_1.25.3 AnnotationDbi_1.51.1    
[85] memoise_1.1.0            cluster_2.1.0            ellipsis_0.3.1  
```

**Comment by mirkocelii** [comment]
Hello, I've had the same problem.
I installed Biocondactor 3.11 and still the CAGEr version present is 1.30.1.
Which is the url foe 1_31 version?
I tried 
https://bioconductor.org/packages/3.11/bioc/src/contrib/CAGEr_1.30.2.tar.gz
https://bioconductor.org/packages/3.11/bioc/src/contrib/CAGEr_1.30.2.tar.gz

**Comment by charles-plessy** [comment]
Hi all, the fixed versions are `1.30.2` for Bioconductor 3.11 (release branch) and  `1.31.3` for Bioconductor 3.12 (devel branch).  In doubt, please use the release branch. By the way, I have just pushed `1.30.3` and `1.31.4`, which correct another bug, which would manifest itself with errors such as `'width(x)' cannot contain negative integers`. So please upgrade in a couple of days.

**Comment by mirkocelii** [comment]
Dear Charles,
I've installed CAGEr 1.30.3 with devotools() and re-run the code.
At the same step where I was getting "width(x)' cannot contain negative integers",  I have this new error:
```
aggregateTagClusters(ce, qLow = 0.1, qUp = 0.9, maxDist = 100)
Error: subscript contains invalid names

```

**Comment by mirkocelii** [comment]
Dear Charles,
I solved that problem, it was the presence of alternative unknown chromosomes (e.g chrUn_KI270754v1)
When I was preparing the subset for you, I saw that on a single chromosome there were no error, and after keeping only CTSS on autosomes X and Y, it worked perfectly.
